### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by HadXu** [upul/Aurora#1]
when I make error following:

nvcc -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=[sm_50,compute_50] -gencode arch=compute_52,code=[sm_52,compute_52] -std=c++11 --compiler-options '-fPIC' -c src/cudnn_operations.cu -o build/obj/cudnn_operations.o
src/cudnn_operations.cu(158): error: too many arguments in function call

src/cudnn_operations.cu(323): error: too many arguments in function call

src/cudnn_operations.cu(445): error: too many arguments in function call

3 errors detected in the compilation of "/tmp/tmpxft_0000171b_00000000-13_cudnn_operations.compute_52.cpp1.ii".
make: *** [build/obj/cudnn_operations.o] Error 2

**Comment by upul** [comment]
Can you please let me know your cuDNN version?

**Comment by HadXu** [comment]
5.1

**Comment by upul** [comment]
I'm using:

CUDA
`upul@upul-GE62VR-7RF:/$ nvcc --version`
`nvcc: NVIDIA (R) Cuda compiler driver`
`Copyright (c) 2005-2016 NVIDIA Corporation`
`Built on Tue_Jan_10_13:22:03_CST_2017`
`Cuda compilation tools, release 8.0, V8.0.61`


cuDNN
`upul@upul-GE62VR-7RF:/$ cat /usr/include/cudnn.h | grep CUDNN_MAJOR -A 2`
`#define CUDNN_MAJOR      6`
`#define CUDNN_MINOR      0`
`#define CUDNN_PATCHLEVEL 21`

Can you please build `Aurora` with above `CUDA` and `cuDNN` versions?

**Comment by upul** [comment]
Answered, hence closing this issue.
